### ISSUE TITLE
Caching of typed in form data

### ISSUE THREAD

**Issue by gman-tools** [electron226/Tab-Memory-Purge#44]
I have just recently started to use your Tab Memory Purge (which is a great idea and welcome tool).  

However, I often blog and while blogging research and curate information, which takes me off the data-entry area of the blog tool I use which is a submission tool that sits in the browser before being committed (submitted) only once to my blog as a blog post.  And, from there I need to go login to the site and edit it from there.

What I have experienced 2-3 times now, is that I have inadvertently stayed away from the tab long enough that is got cached, but the form data did not get cached also so I lost the work.  

Of course I could submit less information earlier, and then go to the blog and continue working there from an earlier point in my process.  This is not always convenient of efficient, and I have just not had to this in the past so have been caught off guard by the caching (which I have set to a higher time interval now).  Much to my chagrin of course, and loss of ideas and time.

This presents a use case, that I would ask you to consider for future feature development.

I would ask that you consider adding that capability to cache the typed-in form data along with the tab is that were possible.

Of course this is a convenience feature, but I would say is one with value.

Thx,
G

**Comment by gman-tools** [comment]
Hey guys, thought I would point you to this chrome extension as a reference design https://chrome.google.com/webstore/detail/lazarus-form-recovery/loljledaigphbcpfhfmgopdkppkifgno?utm_source=chrome-app-launcher-info-dialog

Best, Greg

**Comment by electron226** [comment]
I implemented the function which saving the previous form data when the user purge a tab.
When the purged tab was restored, restores it only once.
The user is able to use this function from the next version.

I thought the previous history function isn't used, such as you showed the extension.
Therefore, it is not implemented for now.
