### ISSUE TITLE
Tabs get lost

### ISSUE THREAD

**Issue by n3oru** [electron226/Tab-Memory-Purge#45]
Hello! Thanks for great addon.
Got issue on two computers under windows 7 - after some time of work most of tabs get lost.

No metter the browser was closed or not - tabs just gone, as they was not opened.

You can catch them from history at the addon's settings page, but this is not good I think.

Thank you.

**Comment by electron226** [comment]
I have not been able to understand better the situation.
However, can you restore the session from the session history of the option page?

**Comment by n3oru** [comment]
Sorry, it's ok, I can do this.

Thank you.

2015-01-17 1:10 GMT+03:00 electron226 <notifications@github.com>:

> I have not been able to understand better the situation.
> However, can you restore the session from the session history of the
> option page?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/electron226/Tab-Memory-Purge/issues/45#issuecomment-70330781>
> .
>



-- 
Григорьев Алексей

**Comment by electron226** [comment]
Ok.
I close this section.
