### ISSUE TITLE
Restarting all tabs

### ISSUE THREAD

**Issue by your4ox** [electron226/Tab-Memory-Purge#46]
All purged tabs automatic restart, when open one of purged tab.
Chromium 45.0.2447.0 and newer https://storage.googleapis.com/chromium-browser-continuous/Win/337205/chrome-win32.zip

**Comment by your4ox** [comment]
is there anybody here?

**Comment by electron226** [comment]
It's the bug.
https://code.google.com/p/chromium/issues/detail?id=520303
https://code.google.com/p/chromium/issues/detail?id=522479

**Comment by electron226** [comment]
The problem has been fixed at Google Chrome 45.0.2454.93.
