### ISSUE TITLE
Not working in latest Chrome dev

### ISSUE THREAD

**Issue by Andreasvb** [electron226/Tab-Memory-Purge#49]
It seems to have stopped working in latest dev, Version 49.0.2593.0 dev-m (64-bit).
Nothing works, can't purge or anything, not sure what's caused it with the update.

**Comment by RJHsiao** [comment]
Same issue for me.

**Comment by electron226** [comment]
The extension had been updated at version 2.4.6.

I installed Chromium version 49.0.2606.0 (32bit).
And It works correctly.

Whether you will work without any problem?

@Andreasvb @RJHsiao

**Comment by Andreasvb** [comment]
Yes, works fine now, thanks!

**Comment by RJHsiao** [comment]
Work fine, too.

Thanks!

**Comment by electron226** [comment]
This problem have fixed. therefore to close.
